### ISSUE TITLE
[RFC] Move document generation to the master branch; require GUID generation on PR branches

### ISSUE THREAD

**Issue by brianebeyer** [redcanaryco/atomic-red-team#1336]
# Proposal:
Require all Atomic Tests to have GUIDs on pull request branches before they can be merged, with a message instructing how to generate GUIDs for a new test if any are missing. Perform doc generation on the master branch after PR merges.

# Reasoning
CI performs two steps for contributors:
1. GUIDs are generated for any Atomic Tests that don't have a GUID specified and the list of used GUIDs is updated
2. Markdown docs and indices are generated from the source Atomic Test YAML files.

These steps are performed after each commit to a PR branch to keep a PR branch up to date as work is performed.

These steps work perfectly for branches from redcanaryco/atomic-red-team because the CI system has permission to commit to that branch. For PR branches on other forks, these steps fail because the CI system does not have permission to change other peoples' branches.

GUID generation is performed by a simple script and only needed when a new test is created, so requiring a contributor to run that script should not substantially impede contributions because tests do not appear to be primarily submitted via the Github web UI (they are done through `bin/new-atomic` or `Atomic GUI` 🔥 ).

Doc generation, on the other hand, results in changes after nearly any change to the repository, and it would meaningfully decrease the contribution experience if we required contributors to run this on their machine before accepting a PR. By moving this to the master branch, it will ensure we have clean docs and significantly clean up the commit history on PR branches.

# Alternatives:
We could move both steps to the master branch so contributors don't have to think about either GUID or Doc generation, but I'm not sure how often GUIDs are required during test development.

We could require both steps be run by contributors on PR branches, but it might meaningfully degrade the experience and contributions.

# How is this RFC resolved?
Reconfiguration of the ART CI system to require and run steps in the appropriate locations.

**Comment by clr2of8** [comment]
Thank you for the great write up. It helped me organize my thoughts as well. Running any of the build scripts on end users systems would be a significant barrier because it would require them to setup a ruby environment plus perform the extra steps. The GUIDS aren't required for local testing and are only there to aid unattended scripted execution of atomics. The most common way that users are creating new atomics today is by copying yaml from one test and editing to meet their needs, including deleting the GUID line. The second most common way is the Atomic GUI which doesn't generate the GUID. I have not known anyone to use the bin/new-atomic script and we don't even talk about using it on the wiki because it is unnecessarily complex. With this in mind, I would love to see both GUID and doc generation committed directly to Master.

**Comment by brianebeyer** [comment]
> With this in mind, I would love to see both GUID and doc generation committed directly to Master.

It sounds like @keithmccammon concurs with this too.

**Comment by brianebeyer** [comment]
## Resolution
We decided to perform Atomic Test validation (not including checking for a GUID) on the PR branch, and move the GUID generation/check and doc generation and their associated commits to the master branch.

## Next Steps
@brianebeyer will implement this in a PR.
