### ISSUE TITLE
Idea:Improve clean for mutliple test

### ISSUE THREAD

**Issue by JiTmun** [redcanaryco/atomic-red-team#1847]
### Use-cases
User run several atomic test from differents techniques, and need to clean after tests.
For now this is done using the following for each technique:
`Invoke-AtomicTest  TXXX.xxx -Cleanup`

### Proposal
- Auto-clean after test have completed
Could be an arg after -Cleanup flag

- Allow -Cleanup to clean several tests afterwards, ex using syntax
`Invoke-AtomicTest   TXXX.xxx, TXXX.xxx, -Cleanup`
`Invoke-AtomicTest   * -Cleanup`

**Comment by clr2of8** [comment]
Hi JiTmum, thanks for the proposal. There is an option to you "ALL" as the technique number and cleanup all Techniques at once. Does this meet your needs? 

There is actually a different GitHub repository for the Invoke-AtomicTest framework [here](https://github.com/redcanaryco/invoke-atomicredteam/issues).  I'm going to close this Issue here but if you would like to continue the discussion you could post the same issue to the link I provided or reach out to OrOneEqualsOne on the Atomic Red Team Slack workspace.
