### ISSUE TITLE
Problem: T1574.006-1 CleanUp not working

### ISSUE THREAD

**Issue by javery-sysdig** [redcanaryco/atomic-red-team#1935]
## What did you do?

Run:  Invoke-AtomicTest T1574.006-1 -CleanUp

## What did you expect to happen?

Remove #{path_to_shared_library} from /etc/ld.so.preload

## What happened instead?

sed syntax error

## Your Environment

- Ubuntu:Focal (20.04 official Docker image)
- As root
- T1574.006

## Proposed Fix

Replace:
`sudo sed -i '\~#{path_to_shared_library}~d' /etc/ld.so.preload`

With:
`sudo sed -i 's##{path_to_shared_library}##' /etc/ld.so.preload`

Tested and works.

**Comment by clr2of8** [comment]
Thanks for reporting this. Making a Pull Request within GitHub in order to contribute a change like this is very easy through the web interface here in GitHub. I've got a demo video showing how to do it [here](https://www.youtube.com/watch?v=EvDYc5oWxdI). You would just need to make the small edit to the T1574.006.yaml file and that is it. Are you interested in giving that a try and becoming a contributor? There's a free Red Canary t-shirt available to first-time contributors.
