### ISSUE TITLE
T1112 Enabling Restricted Admin Mode via Command_Prompt

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#2282]
https://social.technet.microsoft.com/wiki/contents/articles/32905.remote-desktop-services-enable-restricted-admin-mode.aspx

RestrictedAdmin mode prevents the transmission of reusable credentials to the remote system to which you connect using Remote Desktop

So the test should be Disable RestrictedAdmin  so set the key to 1

**Comment by clr2of8** [comment]
This is a little confusing, but from [this link](https://www.kali.org/blog/passing-hash-remote-desktop/) we see what the author of the atomic was going for. 

`It turns out that Microsoft, in their quest to mitigate “Pass-the-Hash” attacks, introduced something called “Restricted Admin” mode.

Inadvertently however, this new security feature actually enabled the use of a password hash for RDP authentication purposes, thereby giving many pentesters once again a reason to smile.`

**Comment by clr2of8** [comment]
To help clarify, I'll add a link to this blog post in the description. Thank you for the feedback.

**Comment by frack113** [comment]
HI,
Thanks for the link.
I have make a [sigma rule](https://github.com/SigmaHQ/sigma/pull/3922) to detect when this feature is enable.
It did not cover the test , but how make a rule to detect when you remove a security to add security 😄
